  version: "3.8"
  services:
    db:
      container_name: postgres_container
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: Mingas
      ports:
        - "5432:5432"
    pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
    spring_application:
      container_name: spring_container
      image: vashaakulka/spring
      depends_on:
        - db
      ports:
        - "8080:8080"